### ISSUE TITLE
question about qwen2-7B

### ISSUE THREAD

**Issue by brisker** [ChenMnZ/PrefixQuant#1]
It seems that, the BOS token is useless for qwen2 (https://github.com/QwenLM/Qwen2.5/issues/486#issuecomment-2153743339), so why does prefixquant regard bos token as prefix token? Simply because it generate larger values at position-down_proj?

**Comment by ChenMnZ** [comment]
For Qwen-2 models, the outlier tokens always and only exist in the initial token. Therefore, set any token as the prefix token is ok.

**Comment by brisker** [comment]
Emm, I am not very sure what you mean.
Can we simply regard prefixQuant as adding several additional tokens for quantization calibration, by replacing the empty kv-cache with prefilled-kv-cache?
Is so, if any token is ok for qwen2 in PrefixQuant, isn't that weird? 

using `tokenizer("我是一只猫")` to quantize is bad, 
but using `tokenizer("我是一只猫猫")` to quantize is good ( since any token  including “ 猫” is ok）

you mean that？

**Comment by ChenMnZ** [comment]
Hi, you can refer the paper for details. 
![image](https://github.com/user-attachments/assets/dfe262db-c3e3-4175-a15b-8ee2b1e7215a)

Some special model, such as Llama-3-8B and Qwen-2-7B, the outlier tokens always and only exist in the initial token, and have nothing to do with the semantics. Therefore, you can prefix any tokens for such model to isolate outliers.

In other words, any initial tokens in Llama-3-8B and Qwen-2-7B would cause upper outlier in the input of down_proj and lower outlier in Q/K. Therefore, if we prefix the initial token in the KV cache, we can avoid the new outliers in both down_proj and Q/K, facilitating per-tensor static quantization.

**Comment by brisker** [comment]
Wouldn't prefix token in the kv-cache change the original fp16 accuracy, since the model forward pipeline seems to be changed?

**Comment by ChenMnZ** [comment]
The influence of prefixed tokens in FP16 models is negligible, less than 0.1 PPL influence in most cases.

You can verify this point by seting quantization bits as 16 and activating prefixed tokens.

**Comment by brisker** [comment]
You mentioned prefixQuant is per-tensor static activation quantization, what about weight? Still per-channel or per-tensor?
If per-channel, will per-tensor-weight-quant even faster? Have you tested this case?

**Comment by ChenMnZ** [comment]
PrefixQuant uses per-channel weight quantization. Our compared object is QuaRot, which also uses per-channel weight quantization. 

I did not test for per-tensor weight quantization. Per-tensor weight quantization must be faster than per-channel quantization. However, the speed difference may be negligible due to they are both static quantization, and both quantization granularity match the output dimension.

**Comment by brisker** [comment]
another weird thing is that, in all the figures you visualized in the paper , why the x-axis is layer, but not token-dim?
I mean, the core idea is to suppress the outlier in a specific linear-layer across tokens, why plot the absmax values across layers? linear-1-layer-quantization has nothing to do with linear-2-layer-quantization, right? We only want to make the absmax values in all tokens for linear-1-layer be more close, so that per-tensor static quantization is easier.
@ChenMnZ

**Comment by ChenMnZ** [comment]
@brisker 
Because I want to show that with PrefixQuant, the absmax values across all layers are reduced.

I have illustrated the ratio between maximum (minimal) value and median value, which reflects the flatness of input activation in each layer.  The smaller maximum ratio across all layers indicates all layers are smooth after prefixquant, leading that we can execute per-tensor static quantization to all layers.

![image](https://github.com/user-attachments/assets/da5e5c30-530a-43df-a0a9-153d55d908c8)
